# Generated by Django 2.0.4 on 2018-04-20 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='dresses')),
                ('size', models.CharField(max_length=2)),
                ('brand', models.CharField(max_length=20)),
                ('occasions', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=30)),
                ('in_use', models.BooleanField(default=False)),
                ('total_likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='media/dresses/')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('seen', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('size', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='notifications',
            name='to_notify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonToNotify', to='tables.UserInfo'),
        ),
        migrations.AddField(
            model_name='collection',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Seller', to='tables.UserInfo'),
        ),
        migrations.AddField(
            model_name='carts',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Username', to='tables.UserInfo'),
        ),
        migrations.AddField(
            model_name='carts',
            name='dressInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='URL', to='tables.Collection'),
        ),
        migrations.AddField(
            model_name='carts',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to='tables.UserInfo'),
        ),
    ]
