# Generated by Django 2.0.13 on 2019-10-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trialDateAndTime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('view1', models.ImageField(blank=True, upload_to='p2d-react/src/dresses/view1')),
                ('view2', models.ImageField(blank=True, upload_to='p2d-react/src/dresses/view2')),
                ('view3', models.ImageField(blank=True, upload_to='p2d-react/src/dresses/view3')),
                ('size', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=20)),
                ('occasions', models.CharField(max_length=70)),
                ('price', models.IntegerField()),
                ('title', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=500)),
                ('availability', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('size', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='carts',
            name='dressesAdded',
            field=models.ManyToManyField(to='tables.Dress'),
        ),
        migrations.AddField(
            model_name='carts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelatedUser', to='tables.UserInfo'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='dressesSelected',
            field=models.ManyToManyField(to='tables.Dress'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserWhoBooked', to='tables.UserInfo'),
        ),
    ]
