# Generated by Django 2.0.13 on 2019-11-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='unavailableDates',
            field=models.CharField(max_length=500),
        ),
    ]
