# Generated by Django 2.0.13 on 2019-10-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='view1',
            field=models.ImageField(blank=True, upload_to='../p2d-react/src/dresses/view1'),
        ),
        migrations.AlterField(
            model_name='dress',
            name='view2',
            field=models.ImageField(blank=True, upload_to='../p2d-react/src/dresses/view2'),
        ),
        migrations.AlterField(
            model_name='dress',
            name='view3',
            field=models.ImageField(blank=True, upload_to='../p2d-react/src/dresses/view3'),
        ),
    ]
