# Generated by Django 2.0.4 on 2018-04-21 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20180421_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Username', to='tables.UserInfo'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='dressInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='URL', to='tables.Collection'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to='tables.UserInfo'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='to_notify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonToNotify', to='tables.UserInfo'),
        ),
    ]
