# Generated by Django 2.0.13 on 2019-11-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20191110_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='rentalHistory',
            field=models.ManyToManyField(related_name='PastRented', to='tables.Dress'),
        ),
        migrations.AddField(
            model_name='carts',
            name='upcomingRentals',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='dressesRented',
            field=models.IntegerField(default=0),
        ),
    ]
