# Generated by Django 2.0.13 on 2019-10-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20191026_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='dressesLiked',
            field=models.ManyToManyField(related_name='LikedDresses', to='tables.Dress'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='dressesAdded',
            field=models.ManyToManyField(related_name='CartDresses', to='tables.Dress'),
        ),
    ]
