# Generated by Django 2.0.4 on 2018-04-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20180421_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
