# Generated by Django 2.0.13 on 2019-11-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20191111_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='numberRented',
            field=models.IntegerField(default=0),
        ),
    ]
