# Generated by Django 2.0.4 on 2018-04-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20180430_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='price',
            field=models.IntegerField(),
        ),
    ]
