# Generated by Django 2.0.13 on 2019-11-15 20:44

from django.db import migrations, models
import tables.models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_userinfo_numberrented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='dressesAdded',
            field=models.ManyToManyField(blank=True, related_name='CartDresses', to='tables.Dress'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='dressesLiked',
            field=models.ManyToManyField(blank=True, related_name='LikedDresses', to='tables.Dress'),
        ),
        migrations.AlterField(
            model_name='dress',
            name='view1',
            field=models.ImageField(blank=True, storage=tables.models.OverwriteStorage(), upload_to='./dresses/view1'),
        ),
        migrations.AlterField(
            model_name='dress',
            name='view2',
            field=models.ImageField(blank=True, storage=tables.models.OverwriteStorage(), upload_to='./dresses/view2'),
        ),
        migrations.AlterField(
            model_name='dress',
            name='view3',
            field=models.ImageField(blank=True, storage=tables.models.OverwriteStorage(), upload_to='./dresses/view3'),
        ),
    ]
