# Generated by Django 2.0.4 on 2018-05-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_auto_20180430_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
