# Generated by Django 2.0.13 on 2019-11-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_auto_20191115_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='dressesAdded',
            field=models.ManyToManyField(null=True, related_name='CartDresses', to='tables.Dress'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='dressesLiked',
            field=models.ManyToManyField(null=True, related_name='LikedDresses', to='tables.Dress'),
        ),
    ]
