# Generated by Django 2.0.13 on 2019-11-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20191115_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='trialDateAndTime',
            field=models.CharField(default='', max_length=10),
        ),
    ]
