# Generated by Django 2.0.4 on 2018-05-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_collection_for_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='occasions',
            field=models.CharField(max_length=70),
        ),
    ]
