# Generated by Django 2.0.13 on 2019-11-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_auto_20191117_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='dateNeeded',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='trialDateAndTime',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
