# Generated by Django 2.0.13 on 2019-06-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_auto_20180502_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='size',
            field=models.CharField(max_length=15),
        ),
    ]
