# Generated by Django 2.0.13 on 2019-11-19 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_auto_20191119_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='dressesAdded',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='dressesLiked',
        ),
    ]
