# Generated by Django 2.0.13 on 2019-06-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_auto_20190618_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
