# Generated by Django 2.0.13 on 2019-11-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_auto_20191119_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='dressesAdded',
            field=models.ManyToManyField(null=True, related_name='CartDresses', to='tables.Dress'),
        ),
        migrations.AddField(
            model_name='carts',
            name='dressesLiked',
            field=models.ManyToManyField(null=True, related_name='LikedDresses', to='tables.Dress'),
        ),
    ]
