# Generated by Django 2.0.13 on 2019-11-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_auto_20191119_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='trialDateAndTime',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carts',
            name='dressesAdded',
            field=models.ManyToManyField(blank=True, related_name='CartDresses', to='tables.Dress'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='dressesLiked',
            field=models.ManyToManyField(blank=True, related_name='LikedDresses', to='tables.Dress'),
        ),
    ]
