# Generated by Django 2.0.13 on 2019-06-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_auto_20190618_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
