# Generated by Django 2.0.13 on 2019-11-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0012_auto_20191119_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='eventId',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
