# Generated by Django 2.0.13 on 2019-06-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0014_auto_20190618_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
